[tool.poetry]
name = "exif_access"
version = "0.1.0"
description = ""
authors = ["ra334"]

[tool.poetry.dependencies]
python = "^3.10"
PyQt5 = "^5.15.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
